openapi: 3.0.3
info:
  title: Voornamen in liedjes API
  version: 1.0.0
  description: API for retrieving songs and artists.

servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.voornameninliedjes.nl
    description: Production server

paths:
  /api/artists:
    get:
      tags:
        - Artists
      summary: Get list of artists
      description: Returns a list of artists with their name and image URL.
      operationId: getApiArtists
      responses:
        '200':
          description: A list of artists.
          content:
            application/vnd.voornameninliedjes.artists.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
        '500':
          description: Server error

components:
  schemas:
    Artist:
      type: object
      properties:
        name:
          type: string
          description: Name of the artist
          example: "John Doe"
        imageUrl:
          type: string
          description: URL to an image of the artist
          format: uri
          example: "https://example.com/images/john_doe.jpg"
