language: java
install: skip

os: linux
dist: xenial
jdk: openjdk17

git:
  depth: false

script:
  - "./gradlew build --scan --no-daemon -s"
  - "./gradlew --no-daemon sonarqube"
addons:
  sonarcloud:
    organization: nl-orangeflamingo
