language: java
install: skip

os: linux
dist: xenial
jdk: openjdk11

git:
  depth: false

script:
  - "./gradlew build --scan -s"
  - "./gradlew --stacktrace sonarqube"
addons:
  sonarcloud:
    organization: nl-orangeflamingo
