language: java
install: skip

os: linux
dist: xenial
jdk: openjdk17

git:
  depth: false

script:
  - "./mvnw clean install"
#  - "./gradlew --no-daemon sonarqube"
addons:
  sonarcloud:
    organization: nl-orangeflamingo
