language: java
install: skip

os: linux
dist: xenial
jdk: openjdk17

git:
  depth: false

script:
  - mvn clean install
#  - "./gradlew --no-daemon sonarqube"
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=nl-orangeflamingo
#addons:
#  sonarcloud:
#    organization: nl-orangeflamingo
