version: '3'
services:
  db:
    image: postgres:15.4-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: vil_app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: voornameninliedjes
    ports:
      - "5432:5432"
  app-jvm:
    image: rweekers/voornameninliedjes-backend:2.1.0-jvm
    user: ${MY_UID}:${MY_GID}
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      logging.file.path: logs
      voornameninliedjes.datasource.application.jdbcUrl: jdbc:postgresql://db:5432/voornameninliedjes
      voornameninliedjes.datasource.migration.jdbcUrl: jdbc:postgresql://db:5432/voornameninliedjes
      voornameninliedjes.images.service.path: http://localhost:8000/images/
    ports:
      - "8080:8080"
    volumes:
      - "./logs-docker:/workspace/logs"
      - "./images:/workspace/images"
    depends_on:
      - db
  app-native:
    image: rweekers/voornameninliedjes-backend:2.1.0-native
    user: ${MY_UID}:${MY_GID}
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      logging.file.path: logs
      server.port: 9000
      voornameninliedjes.datasource.application.jdbcUrl: jdbc:postgresql://db:5432/voornameninliedjes
      voornameninliedjes.datasource.migration.jdbcUrl: jdbc:postgresql://db:5432/voornameninliedjes
      voornameninliedjes.images.service.path: http://localhost:8000/images/
    ports:
      - "9000:9000"
    volumes:
      - "./logs:/workspace/logs"
      - "./images:/workspace/images"
    depends_on:
      - db

  prometheus:
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/config.yml'
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

