version: '3'
services:
  db:
    image: postgres:14.6-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: vil_app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: voornameninliedjes
    ports:
      - "5432:5432"
  app-native:
    image: rweekers/voornameninliedjes-backend:1.3.1-native
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      logging.file.path: logs
      voornameninliedjes.datasource.application.host: db
      voornameninliedjes.datasource.migration.host: db
      voornameninliedjes.images.service.path: http://localhost:8000/images/
    ports:
      - "8080:8080"
    volumes:
      - "./logs-docker:/workspace/logs"
      - "./images:/workspace/images"
    depends_on:
      - db
  app-jvm:
    image: rweekers/voornameninliedjes-backend:1.3.1-jvm
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      logging.file.path: logs
      server.port: 9090
      voornameninliedjes.datasource.application.host: db
      voornameninliedjes.datasource.migration.host: db
      voornameninliedjes.images.service.path: http://localhost:8000/images/
    ports:
      - "9090:9090"
    volumes:
      - "./logs:/workspace/logs"
      - "./images:/workspace/images"
    depends_on:
      - db
