spring:
  flyway:
    locations: classpath:db/migration/{vendor}/prod,classpath:db/migration/{vendor}/dev

voornameninliedjes:
  batch:
    interval: 1000
  cors:
    domains:
      allowed:
        api:
          - http://localhost:3000
          - https://www.voornameninliedjes.nl
          - https://voornameninliedjes.nl
        admin:
          - http://localhost:3000
          - https://beheer.voornameninliedjes.nl
  images:
    service:
      path: http://localhost:8000/images

jobs:
  enabled: false
  enrichSong:
    rate: 60000
  updateSong:
    cron: 10 * * * * MON-FRI