spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: voornameninliedjes
      username: mongoadmin
      password: secret
      authentication-database: admin

# These will be transferred to System properties, see https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration
# These systems properties are uses in log4j2 configuration
logging:
  file:
    path: logs