spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: @spring.profiles.active@
  flyway:
    # Explicit configuration to easily add development data in different profile
    locations: classpath:db/migration/{vendor}/prod
  threads:
    virtual:
      enabled: true

voornameninliedjes:
  datasource:
    application:
      host: localhost
      port: 5432
      database: voornameninliedjes
      schema: vil
      username: vil_app
      password: secret
      pool-name: voornameninliedjes-app-hikari-pool
    migration:
      host: localhost
      port: 5432
      database: voornameninliedjes
      schema: vil
      username: vil_app
      password: secret
      pool-name: voornameninliedjes-migration-hikari-pool
  images:
    service:
      path: https://images.voornameninliedjes.nl
  batch:
    interval: 3000
    service:
      path: https://images.voornameninliedjes.nl
  cors:
    domains:
      allowed:
        api:
          - http://localhost:3000
          - https://alpha.voornameninliedjes.nl
          - https://www.voornameninliedjes.nl
          - https://voornameninliedjes.nl
        admin:
          - http://localhost:3000
          - https://beheer.voornameninliedjes.nl
jobs:
  enabled: true
  enrichSong:
    rate: 3600000
  updateSong:
    cron: 0 50 2 1 * *

# These will be transferred to System properties, see https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.custom-log-configuration
# These systems properties are used in logging configuration
logging:
  file:
    path: logs
