spring:
  output:
    ansi:
      enabled: always
  flyway:
    # Explicit configuration to easily add development data in different profile
    locations: classpath:db/migration/{vendor}/prod

voornameninliedjes:
  datasource:
    application:
      url: jdbc:postgresql://localhost:5432/voornameninliedjes?createDatabaseIfNotExist=true
      schema: vil
      username: vil_app
      password: secret
      pool-name: voornameninliedjes-app-hikari-pool
    migration:
      url: jdbc:postgresql://localhost:5432/voornameninliedjes?createDatabaseIfNotExist=true
      schema: vil
      username: postgres
      password: postgres
      pool-name: voornameninliedjes-migration-hikari-pool
  cache:
    enabled: false
  batch:
    interval: 3000

jobs:
  enabled: true
  enrichSong:
    rate: 3600000
  updateSong:
    cron: 0 50 2 1 * *

# These will be transferred to System properties, see https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration
# These systems properties are uses in log4j2 configuration
logging:
  file:
    path: logs