spring:
  flyway:
    locations: classpath:db/migration/{vendor}/prod,classpath:db/migration/{vendor}/dev

jobs:
  enabled: false
  enrichSong:
    rate: 60000
  updateSong:
    cron: 10 * * * * MON-FRI