spring:
  output:
    ansi:
      enabled: always
  datasource:
    application:
      url: jdbc:postgresql://localhost:5433/voornameninliedjes?createDatabaseIfNotExist=true
      schema: vil
      username: vil_app
      password: secret
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: org.postgresql.Driver
      hikari:
        pool-name: voornameninliedjes-app-hikari-pool
        name: dataSource
        data-source-properties:
          prepareThreshold: 0
    migration:
      url: jdbc:postgresql://localhost:5433/voornameninliedjes?createDatabaseIfNotExist=true
      schema: vil
      username: postgres
      password: postgres
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: org.postgresql.Driver
      hikari:
        pool-name: voornameninliedjes-migration-hikari-pool
        name: migrationDataSource
  data:
    mongodb:
      repositories:
        type: none
      auto-index-creation: false
      host: localhost
      port: 27017
      database: voornameninliedjes
      username: mongoadmin
      password: secret
      authentication-database: admin
  flyway:
    # Explicit configuration to easily add development data in different profile
    locations: classpath:db/migration/{vendor}/prod

jobs:
  enrichSong:
    rate: 60000
  updateSong:
    cron: 10 * * * * MON-FRI

# These will be transferred to System properties, see https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration
# These systems properties are uses in log4j2 configuration
logging:
  file:
    path: logs