spring:
  flyway:
    locations: classpath:db/migration/{vendor}/prod,classpath:db/migration/{vendor}/dev

voornameninliedjes:
  batch:
    interval: 1000

jobs:
  enrichSong:
    enabled: false
    rate: 60000
  updateSong:
    cron: "-"