ALTER TABLE SONGS DROP CONSTRAINT IF EXISTS allowed_status_types;

ALTER TABLE SONGS
    ADD CONSTRAINT allowed_status_types
        CHECK (STATUS = ANY ('{SHOW, IN_PROGRESS, INCOMPLETE, TO_BE_DELETED}'::text[]));

ALTER TABLE SONGS
    ADD COLUMN REMARKS   text;