CREATE TABLE ARTIST_PHOTOS AS
SELECT * FROM ARTIST_WIKIMEDIA_PHOTOS;

ALTER TABLE ARTIST_PHOTOS ADD PRIMARY KEY (id);
ALTER TABLE ARTIST_PHOTOS ADD CONSTRAINT artist_photos_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE;
ALTER TABLE ARTIST_PHOTOS ADD CONSTRAINT artist_photos_url_artist_id_key UNIQUE (url, artist_id);

CREATE SEQUENCE artist_photos_id_seq;
ALTER TABLE ARTIST_PHOTOS ALTER COLUMN id SET DEFAULT nextval('artist_photos_id_seq');
SELECT setval('artist_photos_id_seq', COALESCE((SELECT MAX(id) FROM ARTIST_PHOTOS), 1), true);
