ALTER TABLE SONGS
    ALTER COLUMN STATUS TYPE text;

DROP CAST (varchar AS SONG_STATUS);

DROP TYPE SONG_STATUS;

ALTER TABLE SONGS
    ADD CONSTRAINT allowed_status_types
        CHECK (STATUS = ANY ('{SHOW, IN_PROGRESS, TO_BE_DELETED}'::text[]));