UPDATE SONGS_ARTISTS SET ARTIST = 1740 WHERE ARTIST = 1872;
DELETE FROM ARTIST_LOG_ENTRIES WHERE ARTIST_ID = 1872;
DELETE FROM ARTIST_WIKIMEDIA_PHOTOS WHERE ARTIST_ID = 1872;
DELETE FROM ARTISTS WHERE ID = 1872;