### Get all artists default
GET {{host}}/artists

### Get all artists V1
GET {{host}}/artists
Accept: application/vnd.voornameninliedjes.artists.v1+json

### Get all artists V2
GET {{host}}/artists
Accept: application/vnd.voornameninliedjes.artists.v2+json

### Get artists by id V2
GET {{host}}/artists/4
Accept: application/vnd.voornameninliedjes.artists.v2+json

### Create artist
POST {{host}}/artists
Authorization: Basic {{username}} {{password}}
Accept: application/vnd.voornameninliedjes.artists.v2+json
Content-Type: application/json

{
    "name": "{{artist}}",
    "photos": [
        {
            "url": "https://photo.com/1.jpg",
            "attribution": "Some attribution 1"
        }
    ]
}

### Update artist
PUT {{host}}/artists/9
Authorization: Basic {{username}} {{password}}
Accept: application/vnd.voornameninliedjes.artists.v2+json
Content-Type: application/json

{
    "name": "Nieuwe naam",
    "photos": [
        {
            "url": "https://photo.com/1.jpg",
            "attribution": "Some attribution 1"
        },
        {
            "url": "https://photo.com/2.jpg",
            "attribution": "Some attribution 2"
        }
    ]
}

### Delete artist
DELETE {{host}}/artists/9
Authorization: Basic {{username}} {{password}}
Accept: application/vnd.voornameninliedjes.artists.v2+json
