### Get all songs default
GET {{host}}/songs?name-starts-with=Caroline

### Get all songs V2
GET {{host}}/songs?offset=0&limit=20
Accept: application/vnd.voornameninliedjes.songs.v2+json

### Get filtered songs V2
GET {{host}}/songs?name-starts-with=Ca&offset=0&limit=20
Accept: application/vnd.voornameninliedjes.songs.v2+json

### Get songdetails default
GET {{host}}/songs/the police/roxanne
Accept: application/json

### Get songdetails V2
GET {{host}}/songs/the police/roxanne
Accept: application/vnd.voornameninliedjes.songs.v2+json
