name: Nightly Check Prefix Endpoint

on:
  schedule:
    - cron: '15 3 * * *'  # Every day at 03:15 UTC
  workflow_dispatch:

jobs:
  check-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run prefix endpoint check
        run: |
          chmod +x ./check/check-suggestions.sh
          ./check/check-suggestions.sh
